//Stephen Shoemaker
//Program 6
//CSE 1342
//November 27, 2018
//InHomeEnergy.cpp
//Class definition for InHomeEnergy a derived class of Polluter
//This class stores and calculates the carbon footprint generated by a home
#include "InHomeEnergy.h"
#include <iostream>
using namespace std;

//Stephen Shoemaker
//November 27, 2018
//This function initializes an InHomeEnergy class
//Sets averageElectricBill to double input
InHomeEnergy::InHomeEnergy(double intitialAvgBill){
  averageElectricBill = intitialAvgBill;
}

//Stephen Shoemaker
//November 27, 2018
//Zero Arg constructor for InHomeEnergy
//Sets everageElectricBill to placeholder zero value
InHomeEnergy::InHomeEnergy(){
  averageElectricBill = 0;
}

//Stephen Shoemaker
//November 27, 2018
//This function generates a string that describes the houses carbon footprint
//No paramaters
//returns a string with the carbon footprint
string InHomeEnergy::getCarbonFootprint(){
  //cout << "INHERE" << endl;

  //This needs to be more than one line because the first line isnt recognized
  //as a string until it is added into the output string and cant be added
  //to the second line until it is read as a string
  string output = "This house produces ";
  output += to_string(calculateCarbonFootprint());
  output += " pounds of CO2 per year";

  return output;
}

//Stephen Shoemaker
//November 27, 2018
//Calculates the homes carbon footprint
//no Parameters
//returns the double carbon footprint
double InHomeEnergy::calculateCarbonFootprint(){

  //Average electric bill ÷ average kw/$ * KW emission factor * months in year

  double output = (averageElectricBill / 0.20) * 1.37 * 12;
  return output;
}

//Stephen Shoemaker
//November 27, 2018
//Takes the user data for energy bill
//No Input
//Returns nothing
void InHomeEnergy::inputData(){
  cout << "Getting home emission data" << endl;
  cout << "Average Electric Bill: (Enter as double without dollar sign)";
  cin >> averageElectricBill;
}
